version: 3

tasks:
  default:
    desc: "List available tasks"
    cmds:
      - task --list-all
    silent: true
  ignition-generate:
    desc: "Generate Ignition config using Butane"
    cmds:
      - butane --pretty --strict fcos/k3s.bu.yml > fcos/k3s.ign
      - butane --pretty --strict iso/gh.bu.yml > iso/gh.ign
  download-fcos-iso:
    desc: "Download FCOS ISO"
    cmds:
      -  |
        docker run --security-opt label=disable --pull=always --rm -v ./iso:/data -w /data \
        quay.io/coreos/coreos-installer:release download -s stable -p metal -f iso
      - rm -f iso/*.sig
  generate-password-hash:
    desc: "Generate pass hash using mkpasswd"
    cmds:
      - docker run -ti --rm quay.io/coreos/mkpasswd --method=yescrypt
  embed-ignition:
    desc: "Embed ignition file pointing to Github hosted .ign into ISO"
    cmds:
      -  |
        docker run --security-opt label=disable --pull=always --rm -v ./iso:/data -w /data \
        quay.io/coreos/coreos-installer:release iso customize \
        --dest-ignition gh.ign \
        --dest-device /dev/sda \
        --post-install post_install.sh \
        -f \
        fedora-coreos.iso

  get-kubeconfig:
    desc: "Get k3s kubeconfig and merge it"
    cmds:
      - ssh-keygen -f ~/.ssh/known_hosts -R '192.168.1.30' || true
      - scp -i ~/.ssh/hmlb lab@192.168.1.30:/etc/rancher/k3s/k3s.yaml ~/.kube/homelab
      - sed -i 's/127.0.0.1/192.168.1.30/g' ~/.kube/homelab
  ssh:
    desc: "SSH into homelab"
    cmds:
      - ssh-keygen -f ~/.ssh/known_hosts -R '192.168.1.30' || true
      - ssh -o StrictHostKeyChecking=no -i ~/.ssh/hmlb lab@192.168.1.30
