version: 3

tasks:
  default:
    desc: "List available tasks"
    cmds:
      - task --list-all
    silent: true
  ignition-generate:
    desc: "Generate Ignition config using Butane"
    cmds:
      - butane --pretty --strict fcos/k3s.bu.yml > fcos/k3s.ign
